version: '3'

services:
  app:
    build: .
    container_name: fastapi-app
    network_mode: host
    ports:
      - "8000:000"
    command: bash -c "uvicorn test_project.app:app"
    env_file:
      - .env
    volumes:
      - ./database.sqlite3:/app/database.sqlite3:delegated


